name: LLM Evolution

on:
  push:
    branches:
      - evolve*

jobs:
  evolve:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run LLM Script
        env:
          CO_API_KEY: ${{ secrets.CO_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python evolve.py

      - name: Create Artifact app
        uses: actions/upload-artifact@v4
        with:
          name: evolutions
          path: evolutions/*

      - name: Create Artifact README
        uses: actions/upload-artifact@v4
        with:
          name: README
          path: README.md

      - name: Create Artifact README
        uses: actions/upload-artifact@v4
        with:
          name: CHANGELOG_EVOLUTION
          path: CHANGELOG_EVOLUTION.md

      - name: Push to repo
        run: |
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USER }}
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git add config_local.json CHANGELOG_EVOLUTION.md evolutions/*
          git commit -F iteration_num.txt
          git push
